<%@page import="java.sql.SQLException"%>
<%@page import="org.unicode.cldr.util.VoteResolver.VoterInfo"%>
<%@page import="com.ibm.icu.util.VersionInfo"%>
<%@page import="org.tmatesoft.sqljet.core.internal.lang.SqlParser.commit_stmt_return"%>
<%@page import="java.util.Properties"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	import="org.unicode.cldr.web.*,org.unicode.cldr.util.*,java.io.*"
    pageEncoding="UTF-8"
    %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<%
    CLDRConfig cconfig = CLDRConfig.getInstance();
    File surveyHome = new File(SurveyMain.getSurveyHome());
    String theirVap = cconfig.getProperty("CLDR_VAP", null);
    String vap = request.getParameter("vap");
    File propsFile = new File(surveyHome,CLDRConfigImpl.CLDR_PROPERTIES);
    Properties survProps = new Properties();
    java.io.FileInputStream is = new java.io.FileInputStream(propsFile);
    survProps.load(is);
    // progress.update("Loading configuration..");
    is.close();
    
    final String DOCLINK = "<a href='http://cldr.unicode.org/development'>cldr.unicode.org</a>";
    
    %><%!
    	static void writeProps(Properties survProps, File propsFile, HttpServletRequest request) throws IOException {
    			File backup = new File(propsFile.getParentFile(), propsFile.getName()+".backup");
    			backup.delete();
    			propsFile.renameTo(backup);
			    FileOutputStream os = new FileOutputStream(propsFile);
			    survProps.store(os, "Auto generated by cldr-setup on " + new java.util.Date() + " by " + request.getRemoteAddr());
			    os.close();
   		 }
    %>
    <%

    
String problem = null;

if(!surveyHome.isDirectory()) {
	problem = ("SurveyHome is not a directory - " + surveyHome.getAbsolutePath());
} else {
    File maintFile = SurveyMain.getHelperFile();
    if(!maintFile.exists() && request!=null) {
       SurveyMain.writeHelperFile(request, maintFile);
    }
}
// From here on, we work with the config file manually.


if(theirVap==null) {
    	problem = ("SurveyTool does not yet have a password. Please attempty to view the main page such as <a href='"+request.getContextPath()+"/survey'>here</a> and then try this page again.");
}
if(!theirVap.equals(survProps.getProperty("CLDR_VAP"))) {
	problem = ("Could not re-read raw file " + propsFile.getAbsolutePath() );
}


if(problem != null) {
%>
	<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>CLDR | SurveyTool Configurator | Error</title>
	</head>
	<body>
	<h1>SurveyTool Configurator | Error</h1>
	<p><b>Error:</b><%= problem %></p>
	<hr>
	<a href='<%= request.getContextPath() %>'>Return to the SurveyTool main</a> | See documentation at <%= DOCLINK %>
	</body>
	</html>
<% 
	return; 
	}


	if(!theirVap.equals(vap)) {
%>
	<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>CLDR | SurveyTool Configurator | Login Failure</title>
	</head>
	<body>
	<h1>SurveyTool Configurator | Login Failure</h1>
	<p><b>Error:</b>VAP password Incorrect</p>
		<form action="<%= request.getContextPath()+request.getServletPath() %>" METHOD="POST"><label>CLDR_VAP:<input name='vap' value=''></label><input type='submit' value='Submit'></form>
	<hr>
	<p>If you got here via admin.html, try deleting that file and restarting the server.</p>
	<hr>
	<a href='<%= request.getContextPath() %>'>Return to the SurveyTool main</a> | See documentation at <%= DOCLINK %>
	</body>
	</html>
<%
	return;
	}


    if(!SurveyMain.isMaintenance()) {
		if(request.getParameter("set_maint")!=null) {
			%>
		
			<html>
			<head>
			<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
			<title>CLDR | SurveyTool Configurator | Set Maintenance Mode</title>
			</head>
			<body>
			<h1>SurveyTool Configurator | Set Maintenance Mode</h1>
			
			<%
			{
			    survProps.put("CLDR_MAINTENANCE", "true");
			    writeProps(survProps,propsFile,request);
			    SurveyMain.busted("Restart into maint mode");
			}
			%>
			<h1>Now, restart the web server and then click the following button to configure the survey tool:</h1>
										<form action="<%= request.getContextPath()+request.getServletPath() %>" METHOD="POST"><input name='vap' type='hidden' value='<%= vap %>'>
									<input  type='submit' value='Setup SurveyTool'></form>
		
		
			<hr>
			<a href='<%= request.getContextPath() %>'>Return to the SurveyTool main</a> | See documentation at <%= DOCLINK %>
			</body>
			</html>
			
			<%
			return;
		} else {
			%>
					<html>
					<head>
					<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
					<title>CLDR | SurveyTool Not in Maintenance Mode</title>
					</head>
					<body>
					<h1>SurveyTool Configurator |  SurveyTool Not in Maintenance Mode</h1>
					
					<ul>
						<li>To reconfigure the SurveyTool, click the following button, then restart the web server:
								<form action="<%= request.getContextPath()+request.getServletPath() %>" METHOD="POST"><input name='vap' type='hidden' value='<%= vap %>'>
									<input name='set_maint' type='submit' value='Go into Maintenance Mode'></form>
							</li>
						<li><b>Otherwise</b> to start with a fresh install, delete <%= surveyHome.getAbsolutePath() %> and then restart the survey tool.</li>
					</ul>
					<hr>
					<a href='<%= request.getContextPath() %>'>Return to the SurveyTool main</a> | See documentation at <%= DOCLINK %>
					</body>
					</html>
			<%
			return;
		}
    }

if(request.getParameter("remove_maint")!=null) {
	%>

	<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>CLDR | SurveyTool Configurator | Return to Normal Mode</title>
	</head>
	<body>
	<h1>SurveyTool Configurator | Return to Normal Mode</h1>
	
	<%
	{
	    survProps.put("CLDR_MAINTENANCE", "false");
	    writeProps(survProps,propsFile,request);
	    SurveyMain.busted("Restart out of maint mode");
	}
	%>
	<h1>Now, restart the web server and then click this button to administer:</h1>
										<form action="<%= request.getContextPath() %>/survey?vap=" METHOD="GET">
									<input  type='submit' value='Return to the SurveyTool' /></form>

	<hr>
	<a href='<%= request.getContextPath() %>'>Return to the SurveyTool main</a> | See documentation at <%= DOCLINK %>
	</body>
	</html>
	
	<%
	return;
}
%>

	<html>
	<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>CLDR | SurveyTool Configurator</title>
	</head>
	<body>
	<h1>SurveyTool Configurator</h1>
	
	<h2>Set Parameters</h2>
	<%
	{
		String setupvars[] = {
//				"CLDR_VAP", "Password - can be left alone",
				"CLDR_COMMON", "Where to find the 'common' data. If left at the default, it will be checked out automatically.",
				"CLDR_SEED", "Where to find the 'seed' data. If left at the default, it will be checked out automatically.",
				"CLDR_OLDVERSION", "What is the current version of CLDR? A good value might be " + (VersionInfo.getInstance(CLDRFile.GEN_VERSION).getMajor()-1),
				"CLDR_NEWVERSION", "What is the new version of CLDR? A good value might be " + CLDRFile.GEN_VERSION ,
				"CLDR_MESSAGE",   "You must change this field to be empty to allow normal startup.",
				"CLDR_HEADER", "This is a welcome to your users. Can be blank.",
				"CLDR_PHASE", "Which phase is SurveyTool in? A good option might be: " + org.unicode.cldr.web.SurveyMain.Phase.BETA.name(),
		};
		int which = 0;
		String value = null;
		String field = null;
		String whichT = request.getParameter("which");
		if(whichT!=null) {
			which = Integer.parseInt(whichT);
			if(which<0 || which>(setupvars.length)) {
				which = 0;
			}
		}
		%><form action='<%= request.getContextPath()+request.getServletPath() %>' method='POST'><%
		
		if(which>1) {
		     %>
			     	<button value='<%= which-2 %>' name='which'>Save and Go Back</button>
			     	<hr>
		     <%	
		}
		for(int i=0;i<setupvars.length;i+=2) {
			String param = request.getParameter(setupvars[i]);
			if(param != null) {
				value = WebContext.decodeFieldString(param);				
//				which = i;
				field = setupvars[i];
			}
		}
		if(value!=null && field!=null) {
			if(value.length()==0) {
				survProps.remove(field);
			} else {
				survProps.put(field, value);
			}
			%>Set <tt><%= field %></tt> = <tt><%= value %></tt><br/>Writing propfile..<%
			writeProps(survProps, propsFile, request);
		}
		
		%><div style='padding: 1em; margin: 1em; border: 1px solid gray;'><%
		if(which < setupvars.length) {
			%>
			<hr>
			<h3><tt><%= setupvars[which+0] %></tt> - <%= setupvars[which+1] %></h3>
			<label>Value=<input size='80' name='<%= setupvars[which+0] %>' value='<%= survProps.getProperty(setupvars[which+0], "") %>'></label>
			<hr>
			<%
		} else {
			%>
				Now...
				<ol>
						<li>You must set up the database, see <a href='http://cldr.unicode.org/development/running-survey-tool/cldr-properties/db'>here</a>.
					<% 
						boolean hasDS=false;
						try {
							hasDS = DBUtils.getInstance().hasDataSource();	
						} catch(Throwable t) {
							out.println("Got this error:<pre style='border: 1px solid red; background-color: goldenrod; height: 20em; 	overflow: scroll; font-size: small;'>"+t.toString()+"</pre>");
						}
						if(!hasDS) { %>
						<b>Database source was not found ..</b> 
						<pre><%= DBUtils.getDbBrokenMessage() %></pre>
						<br>
						For MySQL, see the links given here.
						
						<p>
						Restart the web server and reload this page to try again.
						</li>
					<% } else { %>
						<b style='color: green;'>Congratulations! You seem to have a database source up and running.</b>
						<li>That's all! press the <b>Remove Maint Mode</b> button below, and restart your web server!</li>
					<% } %>
					
									
				</ol>
				
				<ol>
				</ol>
				
			<%
		}
		%></div><%
		
		if(which<setupvars.length-1) {
		     %>
		     	<button value='<%= which+2 %>' name='which'>
		     	<b>
		     		Save and Continue (<%= ((setupvars.length-which)/2) + " to go!" %>)
		     		</b>
		     	</button>
		     <%	
		}
	}
	%><input name='vap' type='hidden' value='<%= vap %>'></form>
	
	<hr>
	<p>
		<li>When you are done with ALL items, click this button and then restart the web server:
				<form action="<%= request.getContextPath()+request.getServletPath() %>" METHOD="POST"><input name='vap' type='hidden' value='<%= vap %>'><input name='remove_maint' type='submit' value='Remove Maint Mode'></form>
			</li>
	<hr>
	<a href='<%= request.getContextPath() %>'>Return to the SurveyTool main</a> | See documentation at <%= DOCLINK %>
	</body>
	</html>
